name: CI

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]
  push:
    branches:
      - main

permissions: write-all

jobs:
  CI:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Remove labels, approve CR1 and CR2
        if: ${{ github.event_name != 'pull_request' || (github.event.action != 'labeled' && github.event.action != 'unlabeled') }}
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
      
            const labelsToRemove = ['CR1', 'CR2'];
            for (const label of labelsToRemove) {
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue_number,
                  name: label
                });
              } catch (error) {
              }
            }
            
            try {
              const reviewsResponse = await github.rest.pulls.listReviews({
                owner,
                repo,
                pull_number: issue_number,
              });

              const reviews = reviewsResponse.data;

              for (const review of reviews) {
                if (review.state === 'APPROVED') {
                  await github.rest.pulls.dismissReview({
                    owner,
                    repo,
                    pull_number: issue_number,
                    review_id: review.id,
                    message: 'Automatyczne cofnięcie zatwierdzenia.'
                  });
                }
              }
            } catch (error) {
              console.error('Błąd podczas cofania recenzji:', error);
            }
      - name: Check Labels
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            
            const { data: prLabels } = await github.rest.issues.listLabelsOnIssue({
              owner,
              repo,
              issue_number: prNumber,
            });

            const hasDocumentationLabel = prLabels.some(label => label.name === 'Documentation' || label.name === 'Not Documentation');
            if (!hasDocumentationLabel) {
              core.setFailed('PR musi mieć etykietę DOCUMENTATION lub NOT DOCUMENTATION.');
            }

            const requiredLabels = ['QA Dev', 'CR1', 'CR2'];

            requiredLabels.forEach(label => {
              const hasLabel = prLabels.some(prLabel => prLabel.name === label);

              if (!hasLabel) {
                core.setFailed(`PR nie ma wymaganej etykiety ${label}.`);
              }
            });

            // Pobranie listy wydarzeń związanych z PR
            const events = await github.rest.issues.listEventsForTimeline({
              owner,
              repo,
              issue_number: prNumber,
            });
            events.data.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

            requiredLabels.forEach(label => {
              const labelAddEvent = events.data.find(event => event.event === 'labeled' && event.label.name === label && event.actor.login === context.actor);
              const labelRemoveEvent = events.data.find(event => event.event === 'unlabeled' && event.label.name === label && event.actor.login === context.actor);
              if (labelAddEvent && labelAddEvent.actor.login === context.payload.pull_request.user.login) {
                if (!labelRemoveEvent || labelAddEvent.created_at > labelRemoveEvent.created_at) {
                  core.setFailed(`Nie można samemu sobie nadać labelki ${label}.`);
                }
              }
            });
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Install dependencies via Composer
        run: composer install
      - name: Run cs fixer
        run: composer run-script lint
      - name: Run GrumPHP
        run: |
          vendor/bin/grumphp run

  deploy:
    name: Deploy To Server Dev and Pre
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test/demo-repository
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            composer install
            php artisan migrate
            php artisan config:clear